### ISSUE TITLE
A way to add all Edge colorschemes to Alacritty and select one

### ISSUE THREAD

**Issue by wirerydr** [sainnhe/edge#12]
Hi there - thanks for the awesome Edge colorscheme.  I've been using it quite happily since shortly after you first posted it on GH.

I've been experimenting with Alacritty for the past 2 days, and was thrilled to discover you've already created [Edge schemes](https://github.com/sainnhe/edge/tree/master/alacritty) for it.  In your README, you provide 4 separate schemes, and advise users to choose one and paste into their config.

Alacritty does support multiple themes, so as a slight optimization, if you wanted you could present a single pastable block containing all 4 schemes, and then advise users how they can easily switch between them.  As an added bonus, if the Alacritty setting **`live_config_reload: true`** is active, then they can switch between color schemes with a one-line change, save the file, and see live previews.  

The following is the self-documenting configuration I'm using with my Alacritty:
```yml
### Define your various colour-schemes here, and then choose one with
### the 'colors:' setting below.
schemes:  

  ### Edge (Light variant)
  edge_light:	  &edge_light
    primary:
      background: "0xFAFAFA"
      foreground: "0x4B505B"

    normal:
      black:	  "0x4B505B"
      red:	  "0xD05858"
      green:	  "0x608E32"
      yellow:	  "0xBE7E05"
      blue:	  "0x5079BE"
      magenta:	  "0xB05CCC"
      cyan:	  "0x3A8B84"
      white:	  "0xFAFAFA"

    bright:
      black:	  "0x4B505B"
      red:	  "0xD05858"
      green:	  "0x608E32"
      yellow:	  "0xBE7E05"
      blue:	  "0x5079BE"
      magenta:	  "0xB05CCC"
      cyan:	  "0x3A8B84"
      white:	  "0xFAFAFA"

  ### Edge (Dark Default variant)
  edge_dark_def:  &edge_dark_default
    primary:
      background: '0x1C1C1C'
      foreground: '0xD9D8D8'

    cursor:
     text:	  '0x1C1C1C'
     cursor:	  '0xE7E7E8'

    normal:
      black:	  '0x737371'
      red:	  '0xFB2608'
      green:      '0xA7E22E'
      yellow:	  '0x66D9EE'
      blue:	  '0x009DDC'
      magenta:	  '0xFF55FF'
      cyan:	  '0xFFD204'
      white:      '0xD9D8D8'

    bright:
      black:      '0x737171'
      red:        '0xFB2608'
      green:      '0xA7E22E'
      yellow:     '0x66D9EE'
      blue:       '0x009DDC'
      magenta:    '0xFF55FF'
      cyan:       '0xFFD204'
      white:      '0xFFFFFF'

  ### Edge (Dark Aura variant)
  edge_dark_aura:  &edge_dark_aura
    primary:
      background: "0x2B2D37"
      foreground: "0xC5CDD9"

    normal:
      black:	  "0x363A49"
      red:	  "0xEC7279"
      green:	  "0xA0C980"
      yellow:	  "0xDEB974"
      blue:	  "0x6CB6EB"
      magenta:	  "0xD38AEA"
      cyan:	  "0x5DBBC1"
      white:	  "0xC5CDD9"

    bright:
      black:	  "0x363A49"
      red:	  "0xEC7279"
      green:	  "0xA0C980"
      yellow:	  "0xDEB974"
      blue:	  "0x6CB6EB"
      magenta:	  "0xD38AEA"
      cyan:	  "0x5DBBC1"
      white:	  "0xC5CDD9"

  ### Edge (Dark Neon variant)
  edge_dark_neon:  &edge_dark_neon
    primary:
      background: "0x2B2D3A"
      foreground: "0xC5CDD9"

    normal:
      black:	  "0x363A4E"
      red:	  "0xEC7279"
      green:	  "0xA0C980"
      yellow:	  "0xDEB974"
      blue:	  "0x6CB6EB"
      magenta:	  "0xD38AEA"
      cyan:	  "0x5DBBC1"
      white:	  "0xC5CDD9"

    bright:
      black:	  "0x363A4E"
      red:	  "0xEC7279"
      green:	  "0xA0C980"
      yellow:	  "0xDEB974"
      blue:	  "0x6CB6EB"
      magenta:	  "0xD38AEA"
      cyan:	  "0x5DBBC1"
      white:	  "0xC5CDD9"

### Choose one of the & tags from the schemes listed above
colors: *edge_dark_neon
```
